id: vanilla_recipes
version: 1.0.2
output: build


data_pack:
  load: .
  name: "{{ project_id }}_{{ project_version }}_dp_bundled"

require:
  - weld_deps
  - bolt

pipeline:
  - vanilla_recipes
  - mecha


meta:
  mc_supports: ["1.21.10", "1.21.11", "26.1-snapshot-7"]
  weld_deps:
    enabled: true
    merge_with_weld: false

    deps:
      smithed.crafter.dev: latest
      smithed.custom_block.dev: latest